### PR TITLE
Adapt to tidyr::nest() syntax coming in v1.0.0

### LINKED ISSUE #13: d3_nest() fails with dev tidyr
```R
library(d3r)

titanic_df <- Titanic %>% 
  data.frame() %>% 
  select(Class,Age,Survived,Sex,Freq)

d3_nest(titanic_df, value_cols="Freq", root="titanic")
#> Error: No tidyselect variables were registered
```

Would you mind taking a look? It's probably because I've accidentally broken some aspect of `nest()`, but I can't quite figure out what the code is supposed to be doing

### PR DESCRIPTION
**Pull request by jennybc**
Closes #13

### CODE REVIEW

**Comment by jennybc** [comment]
Sadly, this code *requires* dev tidyr, which will go to CRAN soon.

Which plan do you lean towards?

1. Wait 'til tidyr updates, then update d3r to require that version. We explain that we expect for d3r to be briefly broken in tidyr submission notes.
1. You extend this fix to check for tidyr version and use different syntax to call `nest()`, depending on version. You submit d3r soon.
1. Something else?

**Comment by timelyportfolio** [comment]
@jennybc thanks so much for this.  I have a `develop` branch locally with the fix that I removed temporarily while waiting for `tidyr` release.  I had not thought about checking package version to decide which pattern to use.  I think I like this approach best.  I'll compare mine versus yours and make sure all works with the newest `tidyr`.

**Comment by timelyportfolio** [comment]
@jennybc I have tested https://github.com/timelyportfolio/d3r/commit/029c3459c12a1611d1931e088e19948c92195a40 and seems to work with both new and old syntax.  If I get the nod, then I will close your very generous pull and move forward with this strategy.  I will likely wait until a month passes since last CRAN submit 7/22/2019, update `d3`, and submit with this change.

Thanks again.

**Comment by jennybc** [comment]
Definitely proceed with the code you like best, even if that means closing this unmerged.

We used the revdeps -- including this package, which I looked at very early in this effort -- to organize our heads around some new advice for tidyr usage and migration. Anything inspired by or consistent with the new vignette is likely better than this PR.

Your plan sounds good, although there's no specific reason to wait a whole month. The technical minimum is one week.

**Comment by timelyportfolio** [comment]
@jennybc looks like I just need to wait for CRAN maintenance period to end and then submit.  I will close this.  Appreciate your help.

**Pull request closed without merging**
